openapi: 3.2.0
info:
  title: B2B-OldKAIExtract Metrics API
  description: Extract structured information from documents.
  version: 0.1.0
servers:
- url: https://gateway.api.kuehne-nagel.com/oldkaiextractapi/0.1.0
- url: http://gateway.api.kuehne-nagel.com:8280/oldkaiextractapi/0.1.0
security:
- default: []
tags:
- name: Metrics
paths:
  /metrics:
    get:
      summary: Metrics
      description: Endpoint that serves Prometheus metrics.
      operationId: metrics_metrics_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
      security:
      - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      tags:
      - Metrics
components:
  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://gateway.api.kuehne-nagel.com/authorize
          scopes: {}
x-wso2-api-key-header: ApiKey
